### ISSUE TITLE
Removable drive locked by Skype portable

### ISSUE THREAD

**Issue by epikgit** [portapps/skype-portable#2]
Hi crazy-max,
I'm giving a try to your Skype portable version and it works very well except for a detail. 
If I run Skype portable from a removable drive, I can't eject the drive because it is locked from one of its file.
The file is precisely [drive]:\SkypePortable\data\media-stack\RtcPalVideoEtwSession.etl which is locked by the System process. 
Is there any way to unlock it? 
I tried everything from inside Skype and with third party unlocking software with no luck. The only way to unlock the file and remove the drive is shutting down the PC.

Thanks.

Regards

**Comment by crazy-max** [comment]
Hi @epikgit, can you try to identify the process ? You can use [LockHunter](https://lockhunter.com/) for that.

**Comment by epikgit** [comment]
Already done.
It's System...

**Comment by crazy-max** [comment]
Ok i have flagged some files and identify the issue. The problem seems tp appear when you open a skype VoIP call (file `RtcPalVideoEtwSession.etl` locked).

![image](https://user-images.githubusercontent.com/1951866/43087402-19b4f550-8ea0-11e8-94f0-b4eb1c8f4816.png)

![image](https://user-images.githubusercontent.com/1951866/43087415-20851b9e-8ea0-11e8-90e0-03510dc85046.png)

**Comment by fluggelgleckheimlen** [comment]
You can unlock this file with the following command:
`logman stop RtcPalVideoEtwSession -ets`

**Comment by crazy-max** [comment]
@fluggelgleckheimlen It seems to work thanks!

**Comment by crazy-max** [comment]
Should be fixed now : https://portapps.io/app/skype-portable/#download
